name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      documentId:
        description: 'Either "settings" or "private.secrets"'
        default: 'private.secrets'
        required: true

jobs:
  hello:
    runs-on: ubuntu-latest
    concurrency:
      group: manual
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: node scripts/helloSecrets
        if: ${{ github.event.inputs.documentId == 'private.secrets' }}
        env:
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
          SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
