name: Create Social Image

on:
  workflow_dispatch:
    inputs:
      documentId:
        description: 'Either "settings" or a translation id, for example for norwegian use "settings__i18n_no"'
        default: 'settings'
        required: true

jobs:
  build:
    # runs-on: ubuntu-latest
    # Use the macos machine for now as it has the SF font
    runs-on: macos-latest
    concurrency:
      group: ${{ github.event.inputs.documentId }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run cli:createSocialImage ${{ github.event.inputs.documentId }}
        env:
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
          SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
